

---
experiment:
  root_name: baseline/1hot
  name: x
data:
  key: 1hot-sequence
   # if you insert a new sequence in the student's dictionary, change the key here
ml:
  nfolds: 10
  # test_size: 0.1
  epochs: 30
  oversampler: 
    oversampling_factor: 1.5
    oversampling_col:
      - label
      - language
    rebalancing_mode: equal_balancing # can be minor or major too
    addyourownparameters: helloworld
  splitter:
    stratifier_col: 
      - stratifier_column
seeds:
  splitter: 219
  oversampler: 13
  model: 139
  numpy: 36
...

