---
experiment:
  root_name: labels/break_sequence
  name: x
  type: 1 # 1 to 4
data:
  key: break_sequence
  # available keys: 1hot-sequence, nobreak, nobreak-1hot-sequence, sequence, break_sequence
ml:
  nfolds: 10
  # test_size: 0.1
  epochs: 30 # 30
  oversampler: 
    oversampling_factor: 1.5
    oversampling_col:
      - label
      - language
    rebalancing_mode: equal_balancing # {equal_balancing, minor,  major}
    addyourownparameters: helloworld
  splitter:
    stratifier_col: 
      - stratifier_column
seeds:
  splitter: 219
  oversampler: 13
  model: 139
  numpy: 36
...

