

---
experiment:
  root_name: story/
  name: x
ml:
  nfolds: 3
  test_size: 0.2
  epochs: 1
  oversampler: 
    mode: ros
    oversampling_factor: 1.5
    oversampling_col:
      - label
      - language
    rebalancing_mode: equal_balancing # can be minor or major too
    addyourownparameters: helloworld
  splitter:
    stratifier_col: label
seeds:
  splitter: 21
  oversampler: 13
  model: 139
  numpy: 36
...

