---
experiment:
  root_name: baseline/
  labels: pass
  n_classes: 2
  regexes: 
    - "baseline/(.*)/equal_balancing"
  exclude:
  - exclude
data:
  metrics:
    - roc
    # - recall 
    # - precision
    # - balanced_accuracy
    # - tp 
    # - fp
    # - fn
  fairness_metrics:
    # - fn
    # - tp
    - fp
    # - pp 
    # - recall
    # - precision
    # - balanced_accuracy
    # - roc
  demographics:
    # beerslaw
    # - label
    # - gender
    - language
    # - year
    # - field
  combined_demographics:
    - language
    - label
  exclude_demographics:
    - None
# csv:
#   folder: '../experiments/oversample'
#   file: 'flipped --oversamplingatt gender.country_diploma.tsv'
#   sorting:
#     - metric
#     - baseline
#   baseline: no_os
#   fixed:
#     - key
#     - oversampling_model
#     - oversampling_proportion
#     - oversampling_attribute
#     - metric
#   filtering_experiments:
#     - no_os
#   filtering_columns:
#     - mean
style:
  xspacing: 0.5
  groupspacing: 0.8
  xmargins: 1
  bar_width: 0.09
  figsize_width: 8
  figsize_height: 4 
  rotation: 30
...